const CollectionActionTypes = {
	FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
	FETCH_COLLECTION_PENDING: 'FETCH_COLLECTION_PENDING',
	FETCH_COLLECTION_COMPLETED: 'FETCH_COLLECTION_COMPLETED',
	FETCH_COLLECTION_FAIL: 'FETCH_COLLECTION_FAIL',
};
export default CollectionActionTypes;
